
// Récupéprer toutes les catégories .getAllCategories
GET  http://localhost:3000/category HTTP/1.1

###

POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email" : "test@test.test",
  "password" : "Test123!" 
}


###

// Ajouter une catégorie .createOneCategory
POST  http://localhost:3000/category HTTP/1.1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjksInJvbGUiOjEsImlhdCI6MTcwNjc0NzI5OCwiZXhwIjoxNzA2NzUwODk4fQ.3P1mKkHCvapO2vr_vCfy0gARhHPPg_l-hPymQ6J9XIA 

{
"category_name":"Ecchi"
}
###
// Obtenir les informations d'une catégorie .getOneCategoryById
GET http://localhost:3000/category/7 HTTP/1.1

###
// Modifier une catégorie .modifyOneCategoryById
PATCH http://localhost:3000/category/7 HTTP/1.1
Content-Type: application/json

{
  "category_name": "Hentaï de la muerte"
}

###
// Supprimer une catégorie .removeOneCategoryById
DELETE  http://localhost:3000/category/7 HTTP/1.1