
// Récupéprer tous les états .getAllConditions
GET  http://localhost:3000/condition HTTP/1.1

###
// Ajouter un état .createOneCondition
POST  http://localhost:3000/condition HTTP/1.1
Content-Type: application/json

{
"condition_name":"Comme-Neuf"
}
###
// Obtenir les informations d'un état .getOneConditionById
GET http://localhost:3000/condition/2 HTTP/1.1

###
// Modifier un état .modifyOneConditionById
PATCH http://localhost:3000/condition/4 HTTP/1.1
Content-Type: application/json

{
  "condition_name": "Ultra-Neuf"
}

###
// Supprimer un état .removeOneConditionById
DELETE  http://localhost:3000/condition/4 HTTP/1.1