
// Récupéprer tous les rôles .getAllRoles
GET  http://localhost:3000/role HTTP/1.1

###
// Ajouter un rôle .createOneRole
POST  http://localhost:3000/role HTTP/1.1
Content-Type: application/json

{
"role_name":"SuperAdmin"
}
###
// Obtenir les informations d'un rôle .getOneRoleById
GET http://localhost:3000/role/2 HTTP/1.1

###
// Modifier un rôle .modifyOneRoleById
PATCH http://localhost:3000/role/3 HTTP/1.1
Content-Type: application/json

{
  "role_name": "UltraAdmin"
}

###
// Supprimer un rôle .removeOneRoleById
DELETE  http://localhost:3000/role/3 HTTP/1.1